apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: {{ include "locust.name" . }}
